version: 2
jobs:
  build1:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "A first hello"
  build2:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "A second hello!"
  workflows:
    version: 2
    build1_build2:
      jobs:
        - build1
        - build2
